local config = require('cartograph.config')
local state = require('cartograph.state')

describe('cartograph.state persistence', function()
  before_each(function()
    config.setup({ persist = { dir = vim.fn.tempname() } })
    state.clear()
  end)

  it('saves, lists and loads a named map round-trip', function()
    state.new()
    state.session.graph:add_node({ id = 'a', kind = 'endpoint', name = 'A', file = 'a.cs' })
    state.session.graph:add_node({ id = 'b', kind = 'action', name = 'B' })
    state.session.graph:add_edge({ from = 'a', to = 'b', kind = 'routes-to' })

    assert.is_true(state.save('mymap'))
    assert.are.same({ 'mymap' }, state.list())

    state.clear()
    local s = state.load('mymap')
    assert.is_truthy(s)
    assert.are.equal(2, s.graph:node_count())
    assert.are.equal(1, s.graph:edge_count())
    assert.are.equal('a.cs', s.graph:get_node('a').file)
  end)

  it('lists multiple maps sorted', function()
    state.new()
    state.session.graph:add_node({ id = 'x', kind = 'type', name = 'X' })
    state.save('zeta')
    state.save('alpha')
    assert.are.same({ 'alpha', 'zeta' }, state.list())
  end)

  it('returns an empty list when nothing is saved', function()
    assert.are.same({}, state.list())
  end)

  it('returns nil when loading a missing map', function()
    assert.is_nil(state.load('nope'))
  end)

  it('refuses to save with no active session', function()
    state.clear()
    assert.is_false(state.save('x'))
  end)

  it('rejects names with path traversal on save', function()
    assert.is_false(state.save('../evil'))
    assert.is_false(state.save('a/b'))
    assert.is_false(state.save('a\\b'))
    assert.is_false(state.save('..'))
    assert.is_false(state.save('a.b'))
  end)

  it('rejects names with path traversal on load', function()
    assert.is_false(state.load('../evil'))
    assert.is_false(state.load('a/b'))
    assert.is_false(state.load('..'))
  end)
end)
